name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn
        yarn run build --if-present
        yarn test
      env:
        CI: true
    - name: storybook
      run: yarn run build-storybook
      if: matrix.node-version == '8.x'
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      if: matrix.node-version == '8.x'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: .out
